// Mirrors apps/api/src/config.js ACTIVITY_ACTIONS — the subset of
// phases.md Phase 7's event list actually written today. Extend both
// together as more actions start firing (rules.md §16).
export const ACTIVITY_ACTIONS = {
  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  TASK_COMPLETED: 'TASK_COMPLETED',
  TASK_BLOCKED: 'TASK_BLOCKED',
  TASK_CARRIED_FORWARD: 'TASK_CARRIED_FORWARD',
  TASK_CARRY_FORWARD_DISMISSED: 'TASK_CARRY_FORWARD_DISMISSED',
  TASK_DELETED: 'TASK_DELETED',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DISABLED: 'USER_DISABLED',
  DEPARTMENT_CREATED: 'DEPARTMENT_CREATED',
  DEPARTMENT_UPDATED: 'DEPARTMENT_UPDATED',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  CUSTOM_NOTIFICATION_SENT: 'CUSTOM_NOTIFICATION_SENT',
}

export const ACTIVITY_ACTION_LABELS = {
  [ACTIVITY_ACTIONS.TASK_CREATED]: 'Task created',
  [ACTIVITY_ACTIONS.TASK_UPDATED]: 'Task updated',
  [ACTIVITY_ACTIONS.STATUS_CHANGED]: 'Status changed',
  [ACTIVITY_ACTIONS.TASK_COMPLETED]: 'Task completed',
  [ACTIVITY_ACTIONS.TASK_BLOCKED]: 'Task blocked',
  [ACTIVITY_ACTIONS.TASK_CARRIED_FORWARD]: 'Task carried forward',
  [ACTIVITY_ACTIONS.TASK_CARRY_FORWARD_DISMISSED]: 'Carry-forward dismissed',
  [ACTIVITY_ACTIONS.TASK_DELETED]: 'Task deleted',
  [ACTIVITY_ACTIONS.SETTINGS_UPDATED]: 'Settings updated',
  [ACTIVITY_ACTIONS.USER_CREATED]: 'User added',
  [ACTIVITY_ACTIONS.USER_UPDATED]: 'User updated',
  [ACTIVITY_ACTIONS.USER_DISABLED]: 'User deactivated',
  [ACTIVITY_ACTIONS.DEPARTMENT_CREATED]: 'Department added',
  [ACTIVITY_ACTIONS.DEPARTMENT_UPDATED]: 'Department updated',
  [ACTIVITY_ACTIONS.CATEGORY_CREATED]: 'Category added',
  [ACTIVITY_ACTIONS.CATEGORY_UPDATED]: 'Category updated',
  [ACTIVITY_ACTIONS.CUSTOM_NOTIFICATION_SENT]: 'Notification sent',
}
